### ISSUE TITLE
Unnecessary description() method in Tabs layout

### ISSUE THREAD

**Issue by mauriciomgp5** [alperenersoy/filament-snippets#3]
Hi,

I noticed that when using the "Tab" snippet in the Filament Snippets extension, the generated code includes a `description()` method, which is not a valid method for the `Tabs\Tab` component in the current version of Filament.

Here’s the generated code:
```php
Tabs\Tab::make('Label')
    ->description('')  // This method does not exist in the Tabs\Tab component
    ->schema([
        // Fields here
    ]),
```    

The `description()` method is not part of the Tabs\Tab API and should not be generated by the snippet. It would be great if this could be fixed in a future update.

Thank you for your beautiful work on this extension!

Best regards,
Mauricio G.

**Comment by alperenersoy** [comment]
@mauriciomgp5  removed and published version
